location = /.well-known/assetlinks.json {
    default_type application/json;
    return 200 '[{"relation":["delegate_permission/common.handle_all_urls"],"target":{"namespace":"android_app","package_name":"at.nimmdas.twa","sha256_cert_fingerprints":["2F:D3:CC:A8:EF:50:29:34:D5:80:89:F6:0B:45:3C:DB:B6:3F:ED:D2:15:9D:BF:EA:36:66:2E:04:C3:1C:37:8D"]}}]';
}

location = /nimmdas.apk {
    alias /data/nimmdas.apk;
    default_type application/vnd.android.package-archive;
    add_header Content-Disposition 'attachment; filename="nimmdas.apk"';
}
